SELECT ?id ?date 
WHERE {
  []
    <http://example.com/asio/integration/vocab/PUBLIC_DATETIMES_MOMENT> ?date;
    <http://example.com/asio/integration/vocab/PUBLIC_DATETIMES_ID> ?id.
  FILTER (?date < '1984-11-28T13:00:00'^^xsd:dateTime)
}
